### ISSUE TITLE
[Request] Conda recipe

### ISSUE THREAD

**Issue by PhilipVinc** [google/flax#1178]
Would it be possible for you to release a conda-forge recipe of flax?

We officially released the beta of netket 3, and I was trying to update our conda recipe and since we depend on flax, we need flax to be packaged for conda too.

It's rather an easy process: just run `conda skeleton pypi flax` (flax is just a source package so everything should be smooth) and then open a PR against the right conda repository.

Nowydays, conda reecipes self-update themselves so after setup there would be almost no more maintenance work.

if you want I can also volunteer the work.

**Comment by PhilipVinc** [comment]
I tested a recipe already and it works:

```yaml
{% set name = "flax" %}
{% set version = "0.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: e995c4a40d4790751fbe08a44d7afec6fb22ac3e88a5f7912c40130cef81a3fa

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - dataclasses;python_version <'3.7'
    - jax >=0.2.6
    - matplotlib
    - msgpack
    - numpy >=1.12
    - pip
    - python
  run:
    - dataclasses;python_version <'3.7'
    - jax >=0.2.6
    - matplotlib
    - msgpack
    - numpy >=1.12
    - python

test:
  imports:
    - flax

about:
  home: "https://github.com/google/flax"
  description: |
    Flax: A neural network library for JAX designed for flexibility
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: "Flax: A neural network library for JAX designed for flexibility"
  doc_url: http://flax.readthedocs.io
  dev_url: https://github.com/google/flax

extra:
  recipe-maintainers:
    - PhilipVinc
```
